import { invoke } from "@tauri-apps/api/core";
import type {
  AnalysisEntry,
  AppState,
  InstallPreview,
  MadeFor,
  MergeInputs,
  MergerRep,
  ModRow,
  PlanRoot,
  QueueItem,
  ScriptMergeResult,
  StorageReport,
  UpdateHit,
  XmlMergeResult,
} from "./types";

export const api = {
  frontend_log: (msg: string) => invoke("frontend_log", { msg }),

  open_path: (target: string) => invoke<void>("open_path", { target }),
  open_tool_window: (kind: string, query?: string, path?: string) => invoke("open_tool_window", { kind, query, path }),

  detect_game: () => invoke<string | null>("detect_game"),
  default_prefix: (gameDir: string) => invoke<string | null>("default_prefix", { gameDir }),
  is_game_dir: (path: string) => invoke<boolean>("is_game_dir", { path }),
  open_manager: (gameDir: string, prefix: string, stagingDir: string) => invoke("open_manager", { gameDir, prefix, stagingDir }),
  storage_report: () => invoke<StorageReport>("storage_report"),
  settings_dir_path: () => invoke<string>("settings_dir_path"),
  data_dir_path: () => invoke<string>("data_dir_path"),
  profiles_dir_path: () => invoke<string>("profiles_dir_path"),

  list_mods: () => invoke<AppState>("list_mods"),
  set_enabled: (ids: string[], on: boolean) => invoke("set_enabled", { ids, on }),
  set_priority: (id: string, number: number) => invoke("set_priority", { id, number }),
  remove_mods: (ids: string[]) => invoke("remove_mods", { ids }),
  add_separator: (index: number, name: string) => invoke<ModRow>("add_separator", { index, name }),
  remove_section_cmd: (sepId: string) => invoke("remove_section_cmd", { sepId }),
  move_mod: (id: string, before: string) => invoke("move_mod", { id, before }),
  move_to_section: (id: string, sepId: string) => invoke("move_to_section", { id, sepId }),
  mod_dir: (id: string) => invoke<string>("mod_dir", { id }),
  staged_files: (id: string) => invoke<string[]>("staged_files", { id }),
  clashes: () => invoke<Record<string, string[]>>("clashes"),
  annotation_clashes: () => invoke<Record<string, string[]>>("annotation_clashes"),
  analysis_summary: () => invoke<Record<string, AnalysisEntry>>("analysis_summary"),
  unmanaged_mods: () => invoke<string[]>("unmanaged_mods"),
  import_unmanaged: (rels: string[]) => invoke("import_unmanaged", { rels }),
  made_for: (id: string) => invoke<MadeFor>("made_for", { id }),
  quota: () => invoke<[string, string, number]>("quota"),
  cached_updates: () => invoke<UpdateHit[]>("cached_updates"),
  check_updates: (apiKey: string, ids?: string[]) => invoke("check_updates", { apiKey, ...(ids ? { ids } : {}) }),
  update_mod: (id: string, apiKey: string, premium?: boolean | null) => invoke("update_mod", { id, apiKey, premium }),

  parse_archive_name: (filename: string) => invoke<[string, string, string]>("parse_archive_name", { filename }),
  install_preview: (path: string) => invoke<InstallPreview>("install_preview", { path }),
  remap_roots: (rels: string[], roots: PlanRoot[], modFolder: string) => invoke<string[]>("remap_roots", { rels, roots, modFolder }),
  install_roots: (path: string, name: string, version: string, nexusId: string, section: string, roots: PlanRoot[], replaceIds: string[]) => invoke<string>("install_roots", { path, name, version, nexusId, section, roots, replaceIds }),
  find_collisions: (targets: string[]) => invoke<[string[], string[]]>("find_collisions", { targets }),
  edit_mod: (id: string, name: string, version: string, nexusId: string, section: string) => invoke("edit_mod", { id, name, version, nexusId, section }),

  merge_inputs: (rel: string) => invoke<MergeInputs>("merge_inputs", { rel }),
  merge_xml: (base: string, versions: string[], resolutions: number[]) => invoke<XmlMergeResult>("merge_xml", { base, versions, resolutions }),
  merge_scripts: (baseB64: string[], versionsB64: string[][], resolutions: number[]) => invoke<ScriptMergeResult>("merge_scripts", { baseB64, versionsB64, resolutions }),
  merge_check: (lines: string[]) => invoke<string[]>("merge_check", { lines }),
  save_merge: (rel: string, text: string, answers: unknown[]) => invoke("save_merge", { rel, text, answers }),

  downloads_dir_path: () => invoke<string>("downloads_dir_path"),
  queue_list: () => invoke<QueueItem[]>("queue_list"),
  downloads_history: () => invoke<QueueItem[]>("downloads_history"),
  queue_enqueue: (url: string) => invoke<string>("queue_enqueue", { url }),
  queue_start: (id: string, destDir: string, apiKey: string) => invoke("queue_start", { id, destDir, apiKey }),
  queue_cancel: (id: string) => invoke("queue_cancel", { id }),
  queue_remove: (id: string) => invoke("queue_remove", { id }),
  queue_trash: (id: string, destDir: string) => invoke("queue_trash", { id, destDir }),

  switch_profile: (id: string) => invoke("switch_profile", { id }),
  create_profile: (name: string) => invoke("create_profile", { name }),
  duplicate_profile: (id: string) => invoke("duplicate_profile", { id }),
  rename_profile: (id: string, name: string) => invoke("rename_profile", { id, name }),
  delete_profile: (id: string) => invoke("delete_profile", { id }),

  merger_check: (exePath: string) => invoke<MergerRep>("merger_check", { exePath }),
  merger_apply: (configPath: string, fixes: Record<string, string>) => invoke("merger_apply", { configPath, fixes }),

  game_running: () => invoke<boolean>("game_running"),
  deploy: () => invoke<string[] | { deployed: string[]; removed: string[] }>("deploy"),
};
